### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by envyskins** [thatmitchcanter/twitch-conditional#1]
They must of changed something on Twitch API.  Also, **@file_get_contents** statement is a serious security risk.

If you get this work that would be great.  When it was working it did awesome.

**Comment by thatmitchcanter** [comment]
Hey @envyskins,

I -finally- had some time to fix this. I've swapped out file_get_contents for cURL, and added the API key as a necessity.

Better late than never, right? Thanks for opening an issue.

~Mitch
