### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by sunkast** [thatmitchcanter/twitch-conditional#2]
Plugin no longer works. I think this is due to the new API?

**Comment by sunkast** [comment]
Spent an hour looking up changes and updating the plugin and made a PR. Would be great if it could be udpated to support app tokens in the near future. New API is rate limited to 30 requests per minute for client id but if you use an app token the limit is 120 per minute.

**Comment by openbayou** [comment]
Can you post what you did to get it working again?
